### PR TITLE
Fixes building for base >4,9,0

### PR DESCRIPTION
**Pull request by jappeace**

### CODE REVIEW

**Comment by portnov** [comment]
Hello.
What exactly version of GHC and base are you testing with?

**Comment by jappeace** [comment]
ghc 8.4.3

**Comment by jappeace** [comment]
Yes this maybe a compiler bug. They did qualified instances elsewhere: https://gitlab.haskell.org/ghc/ghc/issues/2237

**Comment by portnov** [comment]
Just tried to change "resolver" field in stack.yaml to "lts-12.14" (which corresponds to 8.4.3 and base-4.11, see here: https://www.stackage.org/lts-12.14), and got no errors...

what exactly error are you getting?

**Comment by jappeace** [comment]
This is the problem I tried to fix:

```shell
Data/Text/Format/Heavy/Types.hs:38:10: error:
    • No instance for (Semigroup Format)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Format’
   |
38 | instance Monoid Format where
   |          ^^^^^^^^^^^^^
builder for '/nix/store/bvzjv4xv33qz1nnh450f6v4hn840nml8-text-format-heavy-0.1.5.1.drv' failed with exit code 1

```


But nevermind I think it's fixed with just plain 1.5.2. Sorry I spend way to long in nix hell yesterday.

**Pull request closed without merging**
